workflows:
  custom_workflow:
    name: Custom Flutter iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ZIP_URL: "https://1fichier.com/?mmkytxngptwhrk2u6s5r"
    scripts:
      - name: Download and unzip project
        script: |
          set -ex
          curl -L -o project.zip "$ZIP_URL"
          mkdir extracted_zip
          unzip -q project.zip -d extracted_zip
          cp -r extracted_zip/* $CM_BUILD_DIR/
          echo "Contenu de $CM_BUILD_DIR :"
          ls -la $CM_BUILD_DIR
          echo "Contenu de $CM_BUILD_DIR/pubspec.yaml :"
          cat $CM_BUILD_DIR/pubspec.yaml
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS app (no codesign)
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
